<?php

namespace FirstBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldRepository extends EntityRepository
{
    
    public function fetchOneWithItems($id){

        $qb = $this ->createQueryBuilder('f')
                    ->leftJoin('f.items', 'i')
                    ->where('f.id = ' . $id)
                    ->addSelect('i');
        
        return $qb->getQuery()->getResult()[0];
     
    }
    
    public function fetchAllWithItems(){

        $qb = $this ->createQueryBuilder('f')
                    ->leftJoin('f.items', 'i')
                    ->orderBy('f.order')
                    ->addSelect('i');
        
        return $qb->getQuery()->getResult();
     
    }
    
    public function fetchAllWithItemsByWorksetId($workset_id){

        $qb = $this ->createQueryBuilder('f')
                    ->leftJoin('f.items', 'i')
                    ->where('f.workset = '.$workset_id)
                    ->orderBy('f.order')    
                    ->addSelect('i');
        
        return $qb->getQuery()->getResult();
     
    }
    
    public function fetchAllByWorksetId($id){
        
        $fields =   $this->findBy(  array('workset' => $id),    //condition
                                    array('order' => 'ASC')     //orderBy
                                 );
        
        return $fields;
    }
}
