<?php

namespace FirstBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldRepository extends EntityRepository
{
    
    public function getSelectListTest1(){
        $qb = $this ->createQueryBuilder('f')
                    ->where('f.id = 1');
        
        return $qb;
    }
}
