<?php

namespace FirstBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * zobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class zobRepository extends EntityRepository
{
}
